### PR TITLE
Fixed Confirm password error

### PR DESCRIPTION
**Pull request by amanpatel123**
In this commit I have fixed the Issue of Confirmation password. Now it is mandatory to have confirm password and also it should match the password mentioned in password field

### CODE REVIEW

**Comment by HarshdipD** [comment]
Hey Aman, I saw the changed files, will the app detect if Password and Confirm Password field are same or different? Did you try that use case?

**Review by HarshdipD — CHANGES_REQUESTED** [review]
I am using `simple_form` gem instead of the default rails form. That's why the syntax is different in `users/new.html.erb`. Can you please revert that back and follow how I'm using other fields?

**Comment by amanpatel123** [comment]
If we use the same syntax as before it is not validating the password. That's why I changed the syntax a little and it worked they way we wanted.

**Comment by HarshdipD** [comment]
> If we use the same syntax as before it is not validating the password. That's why I changed the syntax a little and it worked they way we wanted.

Sounds good. Can you confirm the use case I mentioned earlier?

**Comment by amanpatel123** [comment]
Yes it checks that  Password and Confirm Password field are same or different

**Comment by HarshdipD** [comment]
Awesome - I'll merge it then

**Pull request merged**
